// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNY12blUUkzduPtITjKPz5e2YRSRgqrlY',
    appId: '1:168210903241:web:c5d53ca5eaa508fa471d18',
    messagingSenderId: '168210903241',
    projectId: 'detectoragua',
    authDomain: 'detectoragua.firebaseapp.com',
    databaseURL: 'https://detectoragua-default-rtdb.firebaseio.com',
    storageBucket: 'detectoragua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7K-wL9Pb25JmM2UyNuYXC8NCmJ0Wh5wo',
    appId: '1:168210903241:android:f1f57e5d2abcfebb471d18',
    messagingSenderId: '168210903241',
    projectId: 'detectoragua',
    databaseURL: 'https://detectoragua-default-rtdb.firebaseio.com',
    storageBucket: 'detectoragua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCMBwX7SOilO5K0RKHojcIuzGCbcGb48',
    appId: '1:168210903241:ios:ab2bc05d407311f2471d18',
    messagingSenderId: '168210903241',
    projectId: 'detectoragua',
    databaseURL: 'https://detectoragua-default-rtdb.firebaseio.com',
    storageBucket: 'detectoragua.appspot.com',
    iosBundleId: 'com.example.monitorSensores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCMBwX7SOilO5K0RKHojcIuzGCbcGb48',
    appId: '1:168210903241:ios:adc85caf34823011471d18',
    messagingSenderId: '168210903241',
    projectId: 'detectoragua',
    databaseURL: 'https://detectoragua-default-rtdb.firebaseio.com',
    storageBucket: 'detectoragua.appspot.com',
    iosBundleId: 'com.example.monitorSensores.RunnerTests',
  );
}
